version: '2.1'
orbs:
  node: circleci/node@4.5
jobs:
  test:
    executor:
      name: node/default
      tag: '14.17'
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm run test:ci
      - run: npm run typedoc
      - store_artifacts:
          path: docs
      - store_test_results:
          path: test-results

workflows:
  test_node_sdk:
    jobs:
      - test